# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-diff
  cancel-in-progress: true

jobs:
  diff-generator:
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.2"
    - name: Run generator for this branch
      run: swift run Generator Sources/ExtensionApi/extension_api.json /tmp/NewGenerated
    - name: Checkout target branch
      run: git checkout ${{ github.event.pull_request.base.sha }}
    - name: Run generator again
      run: swift run Generator Sources/ExtensionApi/extension_api.json /tmp/OldGenerated
    - name: Diff output
      run: diff -r /tmp/NewGenerated /tmp/OldGenerated

