# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-diff
  cancel-in-progress: true

jobs:
  diff-generator:
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.2"
    - name: Build This Branch
      run: swift build --target SwiftGodot --scratch-path .build/New
    - name: Checkout Target Branch
      run: git checkout ${{ github.event.pull_request.base.sha }}
    - name: Build Target Branch
      run: swift build --target SwiftGodot --scratch-path .build/Old
    - name: Diff generated
      run: diff -r .build/New/plugins/outputs/swiftgodot/SwiftGodot/destination/CodeGeneratorPlugin/ .build/Old/plugins/outputs/swiftgodot/SwiftGodot/destination/CodeGeneratorPlugin/


